REVOKE ALL ON BEAR FROM PUBLIC;
REVOKE ALL ON BEAR_BEEHIVE FROM PUBLIC;
REVOKE ALL ON BEAR_TYPE FROM PUBLIC;
REVOKE ALL ON BEEHIVE FROM PUBLIC;
REVOKE ALL ON CAVE FROM PUBLIC;

--TABLES

CREATE TABLE EMPLOYEES(
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    PRO_PIC BLOB,
    FIRSTNAME VARCHAR2(100),
    LASTNAME VARCHAR2(100),
    EMAIL VARCHAR2(100) NOT NULL,
    TITLE VARCHAR2(100) DEFAULT 'BARISTA',
    USERNAME VARCHAR2(100) NOT NULL,
    UPASSWORD VARCHAR2(100) NOT NULL,
    MANAGEDBY NUMBER
    );
/

CREATE TABLE REQUESTS(
    REQUEST_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID NUMBER,
    REQUEST DATE NOT NULL,
    REQUEST_STATUS VARCHAR2(100) NOT NULL,
    RECEIPT DATE NOT NULL,
    RECEIPT_IMG BLOB,
    REQUEST_AMT NUMBER(10,2) 
);
/


--CONTRAINTS
ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_MANAGEDBY 
FOREIGN KEY (MANAGEDBY) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE;
/

ALTER TABLE REQUESTS
ADD CONSTRAINT FK_EMPLOYEE_ID 
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)ON DELETE CASCADE;
/


--PROCEDURES

