REVOKE ALL ON BEAR FROM PUBLIC;
REVOKE ALL ON BEAR_BEEHIVE FROM PUBLIC;
REVOKE ALL ON BEAR_TYPE FROM PUBLIC;
REVOKE ALL ON BEEHIVE FROM PUBLIC;
REVOKE ALL ON CAVE FROM PUBLIC;

--TABLES
CREATE TABLE E_LOGIN(
    USERNAME VARCHAR2(100) NOT NULL,
    UPASSWORD VARCHAR2(100) NOT NULL,
    EMPLOYEE_ID NUMBER
);
/

CREATE TABLE EMPLOYEES(
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) DEFAULT 'TEMP',
    FIRSTNAME VARCHAR2(100,
    LASTNAME VARCHAR2(100),
    EMAIL VARCHAR2(100) NOT NULL,
    PRO_PIC BLOB,
    MANAGEDBY NUMBER
    );
/

CREATE TABLE REQUESTS(
    REQUEST_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID NUMBER,
    MANAGEDBY NUMBER,
    RQ_DATE DATE NOT NULL,
    RQ_TYPE VARCHAR2,
    RQ_INFO VARCHAR2,
    RQ_IMG BLOB,
    RQA_AMT NUMBER(10,2), 
    REQUEST_STATUS VARCHAR2(100) DEFAULT 'RECIEVED',
);
/


--CONTRAINTS
ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_MANAGEDBY 
FOREIGN KEY (MANAGEDBY) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE;
/

ALTER TABLE REQUESTS
ADD CONSTRAINT FK_EMPLOYEE_ID 
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)ON DELETE CASCADE;
/


--PROCEDURES

